services:
  spring:
    build: './app'
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - auto_network
    
  
  mysql:
    image: mysql:latest
    container_name: achievements-app
    ports:
      - "3306:3306"

    env_file:
      - "./app/src/main/resources/.env"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 1m30s
      timeout: 15s
      retries: 5
      # start_period: 30s
    networks:
      auto_network:
        ipv4_address: 172.28.0.5
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  auto_network:
   ipam: 
    driver: default
    config: 
    - subnet: 172.28.0.0/16

volumes:
  mysql_data:
    driver: local