apiVersion: v1
kind: Pod
metadata:
  name: mysql-client-pod
spec:
  containers:
    - name: mysql-client
      image: mysql:8
      command: ["sh", "-c", "until mysql -h $MYSQL_HOST -P 3306 -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'; do echo 'Waiting for MySQL...'; sleep 3; done; echo 'Connected to MySQL!'"]
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_ROOT_PASSWORD
