apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: automatyzacja-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: 10.100.200.10
