apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-automatyzacja
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: {{ .Values.app.nodePort}} # Aplikacja działa na tym porcie
  type: NodePort
  externalTrafficPolicy: Local

