app:
  nodePort: 30080
  image:
    repository: mkopczewski/automatyzacja
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1

database:
  image:
    repository: mysql
    tag: 8
    pullPolicy: IfNotPresent
  replicas: 1


secretName: app-secret
configmapName: app-configmap
