app:
  nodePort: 30080
  image:
    repository: mkopczewski/automatyzacja
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1

database:
  image:
    repository: mysql
    tag: 8
    pullPolicy: IfNotPresent
  replicas: 1

ingress:
  enabled: true
  host: "localhost"
  path: "/"
  service:
    name: "app-service"
    port: 80


secretName: app-secret
configmapName: app-config
